language: php

sudo: required

services:
  - mysql

addons:
  postgresql: "9.5"
  firefox: "47.0.1"
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
     - php: 7.1
       env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
     - php: 7.2
       env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0
  - nvm use 14.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//') JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat